### ISSUE TITLE
What is the situation now?

### ISSUE THREAD

**Issue by guotong1988** [howl-anderson/Chinese_models_for_SpaCy#5]
Can we use it now?
@howl-anderson 
Thank you!

**Comment by howl-anderson** [comment]
@guotong1988 Thank you for your attention. Currently (2018-06-07), it's not ready for production using, please visit [todo-list in Chinese](https://github.com/howl-anderson/Chinese_models_for_SpaCy#todo-list) or [todo-list in English](https://github.com/howl-anderson/Chinese_models_for_SpaCy/blob/master/README.en-US.md#todo-list) for more detailed info. Also can I know what's the function or feature do you want most in SpaCy Chinese model? I want know which is the most important feature for down-stream developers.

To community: 
Since many people interested in this project, I will spend more time in this project. If the community can provide more suggestions or resources on corpus, it certainly will accelerate this progress.

**Comment by howl-anderson** [comment]
@guotong1988 Good News: this project is beta ready, OOV and NER issue is fixed. Welcome to try the v2.0.3 model.
